In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
from compactreasoningmodels.datasets.nonogram_dataset import NonogramDataset
import numpy as np

In [3]:
example1 = [
    {
        "rows": [[5],[5],[5],[5],[5]],
        "cols": [[5],[5],[5],[5],[5]],
        "grid": [[1 for _ in range(5)] for _ in range(5)],
        "coolness": 1.0,
        "hello": "world"
    },
    {
        "rows": [[], [], [], [], []],
        "cols": [[], [], [], [], []],
        "grid": [[0 for _ in range(5)] for _ in range(5)]
    },
    {
        "rows": [[], [], [], [], []],
        "cols": [[], [], [], [], []],
        "grid": [[0 for _ in range(5)] for _ in range(5)]
    },
    {
        "rows": [[1], [], [], [], []],
        "cols": [[1], [], [], [], []],
        "grid": [[1, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0],
                 [0, 0, 0, 0, 0]]
    },
]

ex1_ds = NonogramDataset(example1)

In [4]:
print("Example 1 Dataset:")
for i in range(len(ex1_ds)):
    clues, grid, padding_mask, meta = ex1_ds[i]
    print(f"Puzzle {i+1}:")
    print("Clues:", clues)
    print("Grid:")
    print(grid)
    print("Metadata:", meta)
    print("Padding Mask:", padding_mask)
    print()

Example 1 Dataset:
Puzzle 1:
Clues: tensor([5., 0., 0., 5., 0., 0., 5., 0., 0., 5., 0., 0., 5., 0., 0., 5., 0., 0.,
        5., 0., 0., 5., 0., 0., 5., 0., 0., 5., 0., 0.])
Grid:
tensor([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.,
        1., 1., 1., 1., 1., 1., 1.])
Metadata: {'coolness': 1.0, 'hello': 'world', 'shape': torch.Size([5, 5]), 'density': tensor(1.), 'mean_clue_runs': np.float64(1.0)}
Padding Mask: tensor([0., -inf, -inf, 0., -inf, -inf, 0., -inf, -inf, 0., -inf, -inf, 0., -inf, -inf, 0., -inf, -inf, 0., -inf, -inf, 0., -inf, -inf,
        0., -inf, -inf, 0., -inf, -inf])

Puzzle 2:
Clues: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0.])
Grid:
tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0.])
Metadata: {'shape': torch.Size([5, 5]), 'density': tensor(0.), 'mean_clue_runs': np.float64(0.0)}
Padd

In [5]:
import torch


example2 = [[
    [0, 0, 1, 1, 1],
    [0, 0, 1, 1, 1],
    [0, 0, 1, 0, 1],
    [1, 0, 1, 1, 1],
    [0, 1, 1, 1, 1]
],
[
    [1, 0, 1, 1, 1],
    [0, 0, 1, 1, 1],
    [0, 0, 1, 0, 1],
    [1, 0, 1, 1, 1],
    [0, 1, 1, 1, 1]
],
]

example2 = torch.tensor(example2, dtype=torch.float32)

ex2_ds = NonogramDataset(example2, padding="sequence")

In [6]:
print(list(range(len(ex2_ds))))
print(ex2_ds.X.shape)

[0, 1]
torch.Size([2, 120])


In [7]:
print("Example 2 Dataset:")
for i in range(len(ex2_ds)):
    clues, grid, padding_mask, meta = ex2_ds[i]
    print(f"Puzzle {i+1}:")
    print("Clues:", clues)
    print("Grid:")
    print(grid)
    print("Metadata:", meta)
    print("Padding Mask:", padding_mask)
    print()

Example 2 Dataset:
Puzzle 1:
Clues: tensor([3., 0., 0., 0., 3., 0., 1., 0., 1., 0., 2., 0., 1., 0., 2., 1., 1., 0.,
        3., 0., 3., 0., 3., 1., 4., 0., 4., 0., 1., 1., 0., 0., 1., 1., 1., 0.,
        5., 1., 2., 0., 2., 1., 3., 0., 2., 1., 3., 1., 5., 1., 4., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
        0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])
Grid:
tensor([0., 0., 1., 1., 1., 0., 0., 1., 1., 1., 0., 0., 1., 0., 1., 1., 0., 1.,
        1., 1., 0., 1., 1., 1., 1.])
Metadata: {'shape': torch.Size([5, 5]), 'density': tensor(0.6400), 'mean_clue_runs': np.float64(1.3)}
Padding Mask: tensor([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf, -inf,
        -inf, -inf, -inf, -inf, -inf, -inf])

Puzzle 2:
Clues:

In [12]:
example_parquet = NonogramDataset("../data/raw/nng_5x5.parquet", max_size=5)

In [13]:
print("Example parquet Dataset:")
for i in range(len(example_parquet)):
    clues, grid, padding_mask, meta = example_parquet[i]
    print(f"Puzzle {i+1}:")
    print("Clues:", clues)
    print("Grid:")
    print(grid)
    print("Metadata:", meta)
    print("Padding Mask:", padding_mask)
    print()

Example parquet Dataset:
Puzzle 1:
Clues: tensor([1., 1., 0., 3., 0., 0., 2., 0., 0., 2., 0., 0., 2., 1., 0., 1., 0., 0.,
        2., 0., 0., 1., 2., 0., 2., 0., 0., 3., 1., 0.])
Grid:
tensor([1., 0., 0., 0., 1., 0., 0., 1., 1., 1., 0., 0., 0., 1., 1., 0., 1., 1.,
        0., 0., 0., 1., 1., 0., 1.])
Metadata: {'puzzle_id': 0, 'intermediate_solutions': array([array([array([0.2       , 0.14285714, 0.5       , 0.14285714, 1.        ]),
              array([0.11111111, 0.66666667, 1.        , 0.66666667, 1.        ]),
              array([0.07692308, 0.5       , 0.33333333, 0.5       , 1.        ]),
              array([0.07692308, 0.5       , 1.        , 0.5       , 0.        ]),
              array([0.33333333, 1.        , 0.5       , 0.14285714, 1.        ])],
             dtype=object)                                                         ,
       array([array([0.11111111, 0.        , 0.        , 0.        , 1.        ]),
              array([0., 0., 1., 1., 1.]), array([0., 0., 0.,

In [15]:
jsonl_dataset = NonogramDataset("../data/raw/nonogram_5x5.jsonl", max_size=5)

In [16]:
print("Example jsonl Dataset:")
for i in range(len(jsonl_dataset)):
    clues, grid, padding_mask, meta = jsonl_dataset[i]
    print(f"Puzzle {i+1}:")
    print("Clues:", clues)
    print("Grid:")
    print(grid)
    print("Metadata:", meta)
    print("Padding Mask:", padding_mask)
    print()

Example jsonl Dataset:
Puzzle 1:
Clues: tensor([1., 2., 0., 1., 0., 0., 1., 3., 0., 3., 0., 0., 2., 0., 0., 3., 1., 0.,
        1., 0., 0., 1., 2., 0., 1., 2., 0., 2., 0., 0.])
Grid:
tensor([1., 0., 1., 1., 0., 1., 0., 0., 0., 0., 1., 0., 1., 1., 1., 0., 0., 1.,
        1., 1., 1., 1., 0., 0., 0.])
Metadata: {'id': 0, 'height': 5, 'width': 5, 'shape': torch.Size([5, 5]), 'density': tensor(0.5200), 'mean_clue_runs': np.float64(1.5)}
Padding Mask: tensor([0., 0., -inf, 0., -inf, -inf, 0., 0., -inf, 0., -inf, -inf, 0., -inf, -inf, 0., 0., -inf, 0., -inf, -inf, 0., 0., -inf,
        0., 0., -inf, 0., -inf, -inf])

Puzzle 2:
Clues: tensor([2., 0., 0., 3., 1., 0., 2., 1., 0., 2., 1., 0., 1., 1., 0., 1., 2., 0.,
        3., 0., 0., 2., 0., 0., 1., 0., 0., 5., 0., 0.])
Grid:
tensor([0., 0., 0., 1., 1., 1., 1., 1., 0., 1., 0., 1., 1., 0., 1., 1., 1., 0.,
        0., 1., 1., 0., 0., 0., 1.])
Metadata: {'id': 1, 'height': 5, 'width': 5, 'shape': torch.Size([5, 5]), 'density': tensor(0.5600), 'mea